# Generated by Django 5.1.7 on 2025-03-24 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'default_related_name': 'users'},
        ),
        migrations.AlterModelTable(
            name='user',
            table='users_user',
        ),
    ]
