# Generated by Django 5.1.7 on 2025-04-18 13:47

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_date_joined_alter_user_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='items_array',
            field=models.JSONField(default=list, help_text='Array of items associated with the transaction. Each item should have: name, quantity, price, and optional description.', validators=[users.models.validate_items_array]),
        ),
    ]
