# Generated by Django 5.1.7 on 2025-04-19 08:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_transaction_items_array'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanRecord',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='loan_record', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('total_loan', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('cash', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('line_of_credit', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('cash_spent', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('cash_remaining', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('line_of_credit_spent', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('line_of_credit_remaining', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
