# Generated by Django 5.1.7 on 2025-04-26 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('E_Munshi', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoanRecord',
        ),
    ]
