# Generated by Django 5.1.7 on 2025-03-25 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(default='Bank', max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('cnic', models.CharField(max_length=15)),
                ('contact', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('city', models.CharField(max_length=50)),
                ('entity_name', models.CharField(max_length=100)),
                ('yearly_crop_revenue', models.DecimalField(decimal_places=2, max_digits=12)),
                ('yearly_yield', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monthly_net_income', models.DecimalField(decimal_places=2, max_digits=12)),
                ('loan_type', models.CharField(choices=[('crop', 'Crop Loan'), ('equipment', 'Equipment Loan'), ('working_capital', 'Working Capital Loan')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('desired_loan_period', models.IntegerField(help_text='Loan period in months')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
