# Generated by Django 5.1.7 on 2025-04-11 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_Loan', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='loanrequest',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='collateral',
            field=models.TextField(blank=True, help_text='Any collateral tied to the loan', null=True),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='purpose',
            field=models.CharField(blank=True, help_text='Purpose of the loan', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='loanrequest',
            table='loan_requests',
        ),
        migrations.CreateModel(
            name='LoanApproval',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('approved_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Approved loan amount', max_digits=12, null=True)),
                ('interest_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Annual interest rate in percentage', max_digits=5, null=True)),
                ('repayment_terms', models.TextField(blank=True, help_text='Terms and conditions for loan repayment', null=True)),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('pending', 'Pending'), ('rejected', 'Rejected'), ('under_review', 'Under Review'), ('cancelled', 'Cancelled')], default='pending', help_text='Current status of the loan approval', max_length=50)),
                ('approved_at', models.DateTimeField(blank=True, help_text='Timestamp when the loan was approved', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the approval record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the approval record was last updated')),
                ('loan_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='E_Loan.loanrequest')),
            ],
            options={
                'db_table': 'loan_approvals',
                'ordering': ['-created_at'],
                'verbose_name': 'Loan Approval',
                'verbose_name_plural': 'Loan Approvals',
            },
        ),
        migrations.CreateModel(
            name='LoanFinePayment',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('payment_amount', models.DecimalField(decimal_places=2, help_text='Amount of the fine payment', max_digits=12)),
                ('payment_date', models.DateTimeField(help_text='Date and time when the fine payment was made')),
                ('notes', models.TextField(blank=True, help_text='Additional notes or comments about the fine payment', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the fine payment record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when the fine payment record was last updated')),
                ('loan_request', models.ForeignKey(help_text='The loan request this fine payment is associated with', on_delete=django.db.models.deletion.CASCADE, related_name='fine_payments', to='E_Loan.loanrequest')),
            ],
            options={
                'db_table': 'loan_fine_payments',
                'ordering': ['-payment_date'],
                'verbose_name': 'Loan Fine Payment',
                'verbose_name_plural': 'Loan Fine Payments',
            },
        ),
        migrations.AddIndex(
            model_name='loanfinepayment',
            index=models.Index(fields=['loan_request', 'payment_date'], name='loan_fine_p_loan_re_0c0a5c_idx'),
        ),
    ]
