# Generated by Django 5.1.7 on 2025-04-11 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_Loan', '0002_alter_loanrequest_options_loanrequest_collateral_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='loanfinepayment',
            new_name='loan_fine_p_loan_re_8920a5_idx',
            old_name='loan_fine_p_loan_re_0c0a5c_idx',
        ),
    ]
