# Generated by Django 5.1.7 on 2025-04-18 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_Loan', '0003_rename_loan_fine_p_loan_re_0c0a5c_idx_loan_fine_p_loan_re_8920a5_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapproval',
            name='amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount paid by the user', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='loanapproval',
            name='amount_used',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount paid by the user', max_digits=12, null=True),
        ),
    ]
