# Generated by Django 5.1.7 on 2025-04-18 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_Loan', '0004_loanapproval_amount_paid_loanapproval_amount_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapproval',
            name='amount_payable',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount paid by the user', max_digits=12, null=True),
        ),
    ]
