# Generated by Django 5.1.7 on 2025-04-18 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('E_Loan', '0002_loanrequest_status'),
        ('E_Loan', '0005_loanapproval_amount_payable_loanrequest_status'),
    ]

    operations = [
    ]
