# Generated by Django 5.1.7 on 2025-04-18 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_Loan', '0006_merge_20250418_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanrequest',
            name='loan_type',
            field=models.CharField(choices=[('Personal', 'Personal'), ('Agriculture', 'Agricultural'), ('Business', 'Business'), ('Mortgage', 'Mortgage')], max_length=20),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Processing', 'Processing')], default='pending', max_length=20),
        ),
    ]
