# Generated by Django 5.1.7 on 2025-04-24 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('E_Loan', '0007_alter_loanrequest_loan_type_alter_loanrequest_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanfinepayment',
            name='loan_request',
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount paid by the user', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='amount_payable',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total amount payable by the user', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='amount_used',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount used by the user', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='approved_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Approved loan amount', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='approved_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when the loan was approved', null=True),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='interest_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Annual interest rate in percentage', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='loanrequest',
            name='repayment_terms',
            field=models.TextField(blank=True, help_text='Terms and conditions for loan repayment', null=True),
        ),
        migrations.AlterField(
            model_name='loanrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('processing', 'Processing'), ('under_review', 'Under Review'), ('cancelled', 'Cancelled')], default='pending', max_length=50),
        ),
        migrations.DeleteModel(
            name='LoanApproval',
        ),
        migrations.DeleteModel(
            name='LoanFinePayment',
        ),
    ]
